### ISSUE TITLE
NPM version broken?

### ISSUE THREAD

**Issue by tdavis** [minichate/ember-mixpanel#2]
I installed this with `ember install:addon ember-mixpanel` and the resulting `addon.js` contained the line `var mixpanel = window.foo;` which, you might imagine, does not routinely turn out to be the `mixpanel` object. I changed it to `window.mixpanel` which fixed it, came here, and found that it looks fine in the source for 0.0.3. So I guess this is only affecting the NPM version.

**Comment by minichate** [comment]
I'll take a look! Thanks for spotting that

**Comment by minichate** [comment]
Should be fixed in version `0.0.4`. Thanks!
